image:
  file: Dockerfile

tasks:
  - name: Add SSH keys for signing commits
  - before: >
        mkdir -p ~/.ssh &&
        [[ ! -z $GP_SSH_SIGNING_KEY  ]] &&
        echo $GP_SSH_SIGNING_KEY > ~/.ssh/id_rsa.pub &&
        chmod 644 ~/.ssh/id_rsa.pub &&
        [[ ! -z $GP_SSH_SIGNING_PRIVKEY  ]] &&
        echo $GP_SSH_SIGNING_PRIVKEY | base64 -d > ~/.ssh/id_rsa &&
        chmod 600 ~/.ssh/id_rsa
  - name: Fetch juice shop and run it
    init: |
      docker pull bkimminich/juice-shop
    command: |
      docker run --rm -it --env "NODE_ENV=unsafe" -p 3000:3000 bkimminich/juice-shop

gitConfig:
    gpg.format: ssh
    commit.gpgsign: "true"
    user.signingkey: ~/.ssh/id_rsa.pub

ports:
  - name: juice-shop
    description: The web app juice-shop
    port: 3000
    visibility: public
    onOpen: open-preview
